# Generated by Django 5.0.1 on 2024-01-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phn_no', models.CharField(max_length=10)),
                ('skill', models.CharField(choices=[('frontend developer', 'frontend developer'), ('Backend developer', 'Backend developer'), ('Database Adminstrator', 'Database Adminstrator'), ('Non IT Skills', 'Non IT Skills')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('employeeOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
